// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxAssistant.JPK.Database;

#nullable disable

namespace TaxAssistant.JPK.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241117104613_FaCompanyChanges")]
    partial class FaCompanyChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.Ewp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FixedAssetsControlDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RowsControlDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FixedAssetsControlDataId")
                        .IsUnique()
                        .HasFilter("[FixedAssetsControlDataId] IS NOT NULL");

                    b.HasIndex("RowsControlDataId")
                        .IsUnique();

                    b.ToTable("Ewp");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EwpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("EwpId")
                        .IsUnique();

                    b.ToTable("EwpCompany");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpCompanyAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("Voivodeship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EwpCompanyAddress");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpControlData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EwpControlData");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpFixedAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DepreciationRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EwpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("InitialValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UpdatedInitialValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EwpId");

                    b.ToTable("EwpSummary");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EwpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormVariant")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("TaxOfficeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EwpId")
                        .IsUnique();

                    b.ToTable("EwpHeader");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EwpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("RevenueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RevenueTaxed10Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTaxed12Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTaxed12Point5Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTaxed14Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTaxed15Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTaxed17Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTaxed3Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTaxed5Point5Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTaxed8Point5Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EwpId");

                    b.ToTable("EwpRow");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.Fa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fa");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxIdentificationNumberType")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("FaId")
                        .IsUnique();

                    b.ToTable("FaCompany");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaCompanyAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("Voivodeship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FaCompanyAddress");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaControlData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InvoiceRowsCount")
                        .HasColumnType("int");

                    b.Property<int>("InvoicesCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrdersCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalIncomeFromInvoices")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncomeFromOrders")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncomeFromRows")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaId")
                        .IsUnique();

                    b.ToTable("FaControlData");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FormCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormVariant")
                        .HasColumnType("int");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("TaxOfficeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaId")
                        .IsUnique();

                    b.ToTable("FaHeader");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdvanceInvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CashAccountingScheme")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreditNoteChangedDocumentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditNoteChangedDocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditNoteReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ExecutionProcedureIssuerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IntraCommunitySupplyOfGoodsForNewVechicle")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IntraCommunitySupplyOfGoodsForNewVechicleDateOfAprovalToUse")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntraCommunitySupplyOfGoodsForNewVechicleMileage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntraCommunitySupplyOfGoodsForNewVechicleMotohours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IssuedByBuyer")
                        .HasColumnType("bit");

                    b.Property<bool>("IssuedByExecutionProcedure")
                        .HasColumnType("bit");

                    b.Property<bool>("IssuedByNextTaxpayer")
                        .HasColumnType("bit");

                    b.Property<bool>("IssuedByTaxRepresentative")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReversedCharge")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SplitPayment")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TaxRepresentativeIssuerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPriceNetBaseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPriceNetForeignTransaction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPriceNetRate0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPriceNetRate5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPriceNetRate8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPriceNetReverseCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPriceNetVatExempted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVatBaseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalVatBaseRateOtherCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVatForeignTransaction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVatRate5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalVatRate5OtherCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVatRate8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalVatRate8OtherCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVatReverseCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalVatReverseChargeOtherCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("VatExemption")
                        .HasColumnType("bit");

                    b.Property<bool>("VatMarginScheme")
                        .HasColumnType("bit");

                    b.Property<bool>("VatMarginSchemeForTourism")
                        .HasColumnType("bit");

                    b.Property<string>("VatMarginSchemeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VatObjectiveExemptionOtherReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VatObjectiveExemptionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VatSubjectiveExemptionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ExecutionProcedureIssuerId");

                    b.HasIndex("FaId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TaxRepresentativeIssuerId");

                    b.ToTable("FaInvoice");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoiceCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FaInvoiceCompany");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoiceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Count")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetricUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPriceGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPriceNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPriceGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPriceNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VatRate")
                        .HasColumnType("int");

                    b.Property<decimal?>("VatRateSpecial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("FaInvoiceRow");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaId");

                    b.ToTable("FaOrder");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaOrderRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Count")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetricUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalPriceNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalVat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPriceNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VatRate")
                        .HasColumnType("int");

                    b.Property<decimal?>("VatSpecialRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("FaOrderRow");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Import", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EwpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("KpirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EwpId");

                    b.HasIndex("FaId");

                    b.HasIndex("KpirId");

                    b.ToTable("Import");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.Kpir", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kpir");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KpirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalStatisticNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("KpirId")
                        .IsUnique();

                    b.ToTable("KpirCompany");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirCompanyAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LocalNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostOffice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("Voivodeship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KpirComapnyAddress");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirControlData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KpirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KpirId")
                        .IsUnique();

                    b.ToTable("KpirControlData");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormVariant")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KpirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("TaxOfficeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KpirId")
                        .IsUnique();

                    b.ToTable("KpirHeader");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirPhysicalInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KpirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KpirId");

                    b.ToTable("KpirPhisicalInventory");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalField15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CostGoods")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostGoodsRelated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostOther")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostSalaries")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KpirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal?>("ResearchAndDevelopmentCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResearchAndDevelopmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RevenueOther")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KpirId");

                    b.ToTable("KpirRow");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KpirId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhysicalInventoryYearEnd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhysicalInventoryYearStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KpirId")
                        .IsUnique();

                    b.ToTable("KpirSummary");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.Ewp", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpControlData", "FixedAssetsControlData")
                        .WithOne()
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Ewp.Ewp", "FixedAssetsControlDataId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpControlData", "RowsControlData")
                        .WithOne()
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Ewp.Ewp", "RowsControlDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FixedAssetsControlData");

                    b.Navigation("RowsControlData");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpCompany", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpCompanyAddress", "Address")
                        .WithOne("Company")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpCompany", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Ewp.Ewp", "Ewp")
                        .WithOne("Subject")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpCompany", "EwpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Ewp");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpFixedAsset", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Ewp.Ewp", "Ewp")
                        .WithMany("FixedAssets")
                        .HasForeignKey("EwpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ewp");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpHeader", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Ewp.Ewp", "Ewp")
                        .WithOne("Header")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpHeader", "EwpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ewp");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpRow", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Ewp.Ewp", "Ewp")
                        .WithMany("Rows")
                        .HasForeignKey("EwpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ewp");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaCompany", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.FaCompanyAddress", "Address")
                        .WithOne("Company")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Fa.FaCompany", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.Fa", "Fa")
                        .WithOne("Subject")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Fa.FaCompany", "FaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Fa");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaControlData", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.Fa", "Fa")
                        .WithOne("ControlData")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Fa.FaControlData", "FaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fa");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaHeader", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.Fa", "Fa")
                        .WithOne("Header")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Fa.FaHeader", "FaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fa");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoice", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoiceCompany", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId");

                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoiceCompany", "ExecutionProcedureIssuer")
                        .WithMany()
                        .HasForeignKey("ExecutionProcedureIssuerId");

                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.Fa", "Fa")
                        .WithMany("Invoices")
                        .HasForeignKey("FaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoiceCompany", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId");

                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoiceCompany", "TaxRepresentativeIssuer")
                        .WithMany()
                        .HasForeignKey("TaxRepresentativeIssuerId");

                    b.Navigation("Buyer");

                    b.Navigation("ExecutionProcedureIssuer");

                    b.Navigation("Fa");

                    b.Navigation("Seller");

                    b.Navigation("TaxRepresentativeIssuer");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoiceRow", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoice", "Invoice")
                        .WithMany("Rows")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaOrder", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.Fa", "Fa")
                        .WithMany("Orders")
                        .HasForeignKey("FaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fa");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaOrderRow", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.FaOrder", "Order")
                        .WithMany("Rows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Import", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Ewp.Ewp", "Ewp")
                        .WithMany()
                        .HasForeignKey("EwpId");

                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Fa.Fa", "Fa")
                        .WithMany()
                        .HasForeignKey("FaId");

                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Kpir.Kpir", "Kpir")
                        .WithMany()
                        .HasForeignKey("KpirId");

                    b.Navigation("Ewp");

                    b.Navigation("Fa");

                    b.Navigation("Kpir");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirCompany", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirCompanyAddress", "Address")
                        .WithOne("Company")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirCompany", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Kpir.Kpir", "Kpir")
                        .WithOne("Subject")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirCompany", "KpirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Kpir");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirControlData", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Kpir.Kpir", "Kpir")
                        .WithOne("ControlData")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirControlData", "KpirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kpir");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirHeader", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Kpir.Kpir", "Kpir")
                        .WithOne("Header")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirHeader", "KpirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kpir");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirPhysicalInventory", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Kpir.Kpir", "Kpir")
                        .WithMany("PhysicalInventories")
                        .HasForeignKey("KpirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kpir");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirRow", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Kpir.Kpir", "Kpir")
                        .WithMany("Rows")
                        .HasForeignKey("KpirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kpir");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirSummary", b =>
                {
                    b.HasOne("TaxAssistant.JPK.Shared.Model.Database.Kpir.Kpir", "Kpir")
                        .WithOne("Summary")
                        .HasForeignKey("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirSummary", "KpirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kpir");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.Ewp", b =>
                {
                    b.Navigation("FixedAssets");

                    b.Navigation("Header")
                        .IsRequired();

                    b.Navigation("Rows");

                    b.Navigation("Subject")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Ewp.EwpCompanyAddress", b =>
                {
                    b.Navigation("Company")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.Fa", b =>
                {
                    b.Navigation("ControlData")
                        .IsRequired();

                    b.Navigation("Header")
                        .IsRequired();

                    b.Navigation("Invoices");

                    b.Navigation("Orders");

                    b.Navigation("Subject")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaCompanyAddress", b =>
                {
                    b.Navigation("Company")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaInvoice", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Fa.FaOrder", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.Kpir", b =>
                {
                    b.Navigation("ControlData")
                        .IsRequired();

                    b.Navigation("Header")
                        .IsRequired();

                    b.Navigation("PhysicalInventories");

                    b.Navigation("Rows");

                    b.Navigation("Subject")
                        .IsRequired();

                    b.Navigation("Summary")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxAssistant.JPK.Shared.Model.Database.Kpir.KpirCompanyAddress", b =>
                {
                    b.Navigation("Company")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
